In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

In [2]:
df = pd.read_csv('Medium_Clean.csv')
df.head()

c:\program files\python37\lib\site-packages\IPython\core\interactiveshell.py:3044: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,Title,Subtitle,Image,Author,Publication,Year,Month,Day,Reading_Time,...,Tag_travel,Tag_trump,Tag_ux,Tag_venture-capital,Tag_web-design,Tag_web-development,Tag_women,Tag_wordpress,Tag_work,Tag_writing
0,2,Online Animation: Mixamo vs Norah AI,Online animations tools provide game designers...,1,Emma Laurent,NaN,2017,8,1,5,...,0,0,0,0,0,0,0,0,0,0
1,5,A.I. ?,NaN,0,Sanparith Marukatat,NaN,2017,8,1,2,...,0,0,0,0,0,0,0,0,0,0
2,11,"Futures of AI, Friendly AI?",From Physics of the Future: How Science Will S...,1,Z,NaN,2017,8,1,3,...,0,0,0,0,0,0,0,0,0,0
3,12,The Value Generated through AI led Mindfulness,A true product co-created by the Millennials,1,Emiko Sawaguchi,MILLENNIALSTIMES,2017,8,1,5,...,0,0,0,0,0,0,0,0,0,0
4,17,"Os Melhores Links de JulhoCmeras Vintage, Goog...",mas pera a?,1,Giovani Ferreira,NEW ORDER,2017,8,1,3,...,0,0,0,0,0,0,0,0,0,0

In [3]:
__df = df.drop(df.columns[2:13], axis=1)
__df.head()

,Unnamed: 0,Title,Tag_ai,Tag_android,Tag_apple,Tag_architecture,Tag_art,Tag_artificial-intelligence,Tag_big-data,Tag_bitcoin,...,Tag_travel,Tag_trump,Tag_ux,Tag_venture-capital,Tag_web-design,Tag_web-development,Tag_women,Tag_wordpress,Tag_work,Tag_writing
0,2,Online Animation: Mixamo vs Norah AI,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,5,A.I. ?,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,11,"Futures of AI, Friendly AI?",1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,12,The Value Generated through AI led Mindfulness,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,17,"Os Melhores Links de JulhoCmeras Vintage, Goog...",1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
def rev_onehot(row):
    for c in __df.columns[2:]:
        if row[c]==1:
            return c

tagged_list = __df.apply(rev_onehot, axis=1)
print(tagged_list)

0                               Tag_ai
1                               Tag_ai
2                               Tag_ai
3                               Tag_ai
4                               Tag_ai
                      ...
1391028    Tag_artificial-intelligence
1391029                      Tag_apple
1391030                   Tag_blogging
1391031                   Tag_blogging
1391032                   Tag_blogging
Length: 1391033, dtype: object

In [5]:
main_df = pd.DataFrame(columns=['Url', 'Claps', 'Tag'])
main_df['Url'] = df['url']
main_df['Claps'] = df['Claps']
main_df['Tag'] = tagged_list
main_df.head()

                                                 Url  Claps     Tag
0  https://medium.com/@laurentemma/online-animati...   12.0  Tag_ai
1  https://medium.com/@sanparithmarukatat/a-i-%E0...   11.0  Tag_ai
2  https://medium.com/@otherside914/futures-of-ai...    1.0  Tag_ai
3  https://millennials-times.com/creativeflower-e...    4.0  Tag_ai
4  https://medium.com/neworder/os-melhores-links-...   56.0  Tag_ai

In [6]:
#main_df.to_csv('Medium-Clean-Reduced.csv')

In [7]:
test_df = main_df.set_index('Url').groupby('Tag')['Claps'].nlargest(10).reset_index()
test_df

             Tag                                                Url    Claps
0         Tag_ai  https://medium.com/@kaistinchcombe/decentraliz...  53000.0
1         Tag_ai  https://medium.com/@theanythingapp/fast-forwar...  42000.0
2         Tag_ai  https://medium.com/predict/are-programmers-hea...  23000.0
3         Tag_ai  https://medium.com/swlh/chatbots-were-the-next...  19200.0
4         Tag_ai  https://medium.com/@WisewolfFund_io/unique-tre...  18300.0
..           ...                                                ...      ...
945  Tag_writing  https://medium.com/the-mission/six-rules-for-w...   8200.0
946  Tag_writing  https://medium.com/@carlymaedee/a-life-changin...   6600.0
947  Tag_writing  https://textio.ai/1000-different-people-the-sa...   5400.0
948  Tag_writing  https://hackernoon.com/5-myths-about-exposure-...   4800.0
949  Tag_writing  https://medium.com/s/story/i-shared-my-sex-lif...   4500.0

[950 rows x 3 columns]

In [8]:
test_df.groupby('Tag').count()

                     Url  Claps
Tag
Tag_ai                10     10
Tag_android           10     10
Tag_apple             10     10
Tag_architecture      10     10
Tag_art               10     10
...                  ...    ...
Tag_web-development   10     10
Tag_women             10     10
Tag_wordpress         10     10
Tag_work              10     10
Tag_writing           10     10

[95 rows x 2 columns]

In [11]:
exp_df = test_df.sample(frac=1).reset_index(drop=True)
exp_df

,Tag,Url,Claps
0,Tag_blacklivesmatter,https://medium.com/@DeepGreenPhilly/withering-...,20000.0
1,Tag_leadership,https://medium.com/personal-growth/if-you-dont...,59000.0
2,Tag_ethereum,https://medium.com/rubius-inc/why-merchants-ar...,22000.0
3,Tag_parenting,https://medium.com/the-establishment/when-your...,8000.0
4,Tag_poetry,https://medium.com/@caityjohnstone/new-years-r...,4800.0
...,...,...,...
945,Tag_movies,https://medium.com/@josvchoi/the-last-jedi-on-...,5400.0
946,Tag_investing,https://medium.com/darius-foroux/how-i-build-w...,13300.0
947,Tag_venture-capital,https://medium.com/dfinity/announcing-dfinity-...,3700.0
948,Tag_sports,https://medium.com/the-lily/serena-williams-sh...,1800.0
949,Tag_art,https://medium.com/personal-growth/a-quick-beg...,118000.0

In [12]:
exp_df.to_csv('Export-Medium-Data-950.csv')